apiVersion: v1
kind: Service
metadata:
  name: {{ include "ballast-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ballast-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ballast-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
