#!/usr/bin/env bash
# Format an RCA JSON file as a GitHub issue body.
set -euo pipefail
RCA_FILE="${1:?RCA JSON path required}"
jq -r '
  "**Incident:** `" + .investigation_id + "` · **" + .service + "** / `" + .namespace + "`\n\n" +
  "## Incident summary\n\n" + .summary + "\n\n" +
  "**Confidence:** " + (.confidence.score * 100 | tostring) + "% — " + .confidence.rationale + "\n\n" +
  "## Rollout correlation\n\n" +
  "- Rollout: `" + .rollout_correlation.rollout_at + "`\n" +
  "- Alert: `" + .rollout_correlation.alert_fired_at + "`\n" +
  "- Delta: " + (.rollout_correlation.delta_seconds | tostring) + "s (" +
    (if .rollout_correlation.correlated then "correlated" else "not correlated" end) + ")\n\n" +
  "## Resource regression\n\n" +
  "`" + .resource_change.field + "`: **" + .resource_change.previous + "** → **" + .resource_change.current + "**\n\n" +
  .resource_change.note + "\n\n" +
  "## Recommended action\n\n" +
  "**" + .recommended_action.action + "** — " + .recommended_action.reasoning + "\n\n" +
  "```bash\n" + .recommended_action.remediation + "\n```\n\n" +
  "---\n*Generated by Ballast (" + .generated_by + ") — incident `" + .investigation_id + "`*"
' "${RCA_FILE}"
